"""entries

Revision ID: 097aee9a73aa
Revises: 2c26d29416b2
Create Date: 2026-07-02 15:05:02.904589
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "097aee9a73aa"
down_revision: str | None = "2c26d29416b2"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "entries",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("date", sa.Date(), nullable=False),
        sa.Column("start_minute", sa.Integer(), nullable=False),
        sa.Column("end_minute", sa.Integer(), nullable=True),
        sa.Column("timesheet_code_id", sa.Integer(), nullable=True),
        sa.Column("activity", sa.String(length=255), nullable=True),
        sa.Column("description", sa.String(length=1000), nullable=True),
        sa.Column(
            "created_at", sa.DateTime(timezone=True), server_default=sa.text("(CURRENT_TIMESTAMP)"), nullable=False
        ),
        sa.Column(
            "updated_at", sa.DateTime(timezone=True), server_default=sa.text("(CURRENT_TIMESTAMP)"), nullable=False
        ),
        sa.ForeignKeyConstraint(
            ["timesheet_code_id"],
            ["timesheet_codes.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_entries_date"), "entries", ["date"], unique=False)
    op.create_index(op.f("ix_entries_timesheet_code_id"), "entries", ["timesheet_code_id"], unique=False)
    op.create_index(op.f("ix_entries_user_id"), "entries", ["user_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_entries_user_id"), table_name="entries")
    op.drop_index(op.f("ix_entries_timesheet_code_id"), table_name="entries")
    op.drop_index(op.f("ix_entries_date"), table_name="entries")
    op.drop_table("entries")
    # ### end Alembic commands ###
