"""checklist marks

Revision ID: 857bcfc43322
Revises: 097aee9a73aa
Create Date: 2026-07-02 15:35:12.465049
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "857bcfc43322"
down_revision: str | None = "097aee9a73aa"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "checklist_marks",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("fortnight_start", sa.Date(), nullable=False),
        sa.Column("timesheet_code_id", sa.Integer(), nullable=False),
        sa.Column("activity", sa.String(length=255), nullable=False),
        sa.Column("day", sa.Integer(), nullable=False),
        sa.Column("entered", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at", sa.DateTime(timezone=True), server_default=sa.text("(CURRENT_TIMESTAMP)"), nullable=False
        ),
        sa.Column(
            "updated_at", sa.DateTime(timezone=True), server_default=sa.text("(CURRENT_TIMESTAMP)"), nullable=False
        ),
        sa.ForeignKeyConstraint(
            ["timesheet_code_id"],
            ["timesheet_codes.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "user_id", "fortnight_start", "timesheet_code_id", "activity", "day", name="uq_checklist_mark"
        ),
    )
    op.create_index(op.f("ix_checklist_marks_fortnight_start"), "checklist_marks", ["fortnight_start"], unique=False)
    op.create_index(op.f("ix_checklist_marks_user_id"), "checklist_marks", ["user_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_checklist_marks_user_id"), table_name="checklist_marks")
    op.drop_index(op.f("ix_checklist_marks_fortnight_start"), table_name="checklist_marks")
    op.drop_table("checklist_marks")
    # ### end Alembic commands ###
