"""task recurrence rule

Revision ID: c78f0831d366
Revises: 19677d96f929
Create Date: 2026-07-03 21:37:57.580990
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "c78f0831d366"
down_revision: str | None = "19677d96f929"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("tasks", sa.Column("recurrence_rule", sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("tasks", "recurrence_rule")
    # ### end Alembic commands ###
