"""reference codes

Revision ID: ee96a7476366
Revises: 3636fb0361b3
Create Date: 2026-07-02 18:29:07.796678
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "ee96a7476366"
down_revision: str | None = "3636fb0361b3"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "reference_codes",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("number", sa.String(length=50), nullable=False),
        sa.Column("label", sa.String(length=255), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("activities", sa.JSON(), nullable=False),
        sa.Column(
            "created_at", sa.DateTime(timezone=True), server_default=sa.text("(CURRENT_TIMESTAMP)"), nullable=False
        ),
        sa.Column(
            "updated_at", sa.DateTime(timezone=True), server_default=sa.text("(CURRENT_TIMESTAMP)"), nullable=False
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_id", "number", name="uq_reference_code_user_number"),
    )
    op.create_index(op.f("ix_reference_codes_number"), "reference_codes", ["number"], unique=False)
    op.create_index(op.f("ix_reference_codes_user_id"), "reference_codes", ["user_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_reference_codes_user_id"), table_name="reference_codes")
    op.drop_index(op.f("ix_reference_codes_number"), table_name="reference_codes")
    op.drop_table("reference_codes")
    # ### end Alembic commands ###
